version: '2'
networks:
  lb_web:
    external: true
  back:
    driver: bridge
services:
  web:
    image: nginx
    links:
      - app
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    environment:
      - forum.thecloudseminar.com
    ports:
      - "80:80"
    networks:
    - back
    - lb_web
  app:
    image: cloudgenius/discourseimage
    volumes:
      - ./data/assets:/home/discourse/discourse/public/assets
      - ./data/uploads:/home/discourse/discourse/public/uploads
      - ./data/backups:/home/discourse/discourse/public/backups
    links:
      - forumpostgres
      - forumredis
    env_file:env
      - ./env
    environment:
      - DISCOURSE_HOSTNAME=forum.thecloudseminar.com
    networks:
    - back
  sidekiq:
    image: cloudgenius/discourseimage
    command: bundle exec sidekiq -q critical -q default -q low -v
    links:
      - forumpostgres
      - forumredis
    env_file:
      - ./env
    environment:
      - DISCOURSE_HOSTNAME=forum.thecloudseminar.com
    volumes_from:
      - app
    networks:
    - back
  forumpostgres:
    image: postgres:9.4.8
    env_file:
      - ./env
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    networks:
    - back
  forumredis:
    image: redis
    networks:
    - back
